# ref: https://graspingtech.com/ansible-nginx-static-site/

- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  # - name: "install nginx"
  #   apt:
  #     name: ['nginx']
  #     state: latest

  - name: "create www directory"
    file:
      path: /var/www/{{ domain }}
      state: directory
      mode: '0775'
      # owner: "{{ ansible_user }}"
      # group: "{{ ansible_user }}"

  - name: "create imgages directory"
    file:
      path: /var/www/{{ domain }}/images
      state: directory
      mode: '0775'
      # owner: "{{ ansible_user }}"
      # group: "{{ ansible_user }}"      

  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  - name: Download nginx config file
    get_url:
      url: https://raw.githubusercontent.com/carlosggomes/ibm-cloud-demo-ansible/main/templates/site.conf.j2
      dest: /etc/nginx/sites-enabled/{{ domain }}

  - name: Download nginx index.html
    get_url:
      url: https://raw.githubusercontent.com/carlosggomes/ibm-cloud-demo-ansible/main/site/index.html
      dest: /var/www/{{ domain }}/index.html

  - name: Download nginx image
    get_url:
      url: https://github.com/carlosggomes/ibm-cloud-demo-ansible/blob/main/site/images/image001.png
      dest: /var/www/{{ domain }}/images/image001.png


  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

  # - name: "sync website"
  #   synchronize:
  #     src: https://github.com/carlosggomes/ibm-cloud-demo-ansible/tree/main/site/
  #     dest: /var/www/{{ domain }}
  #     archive: no
  #     checksum: yes
  #     recursive: yes
  #     delete: yes
  #   become: no